import { readdir, readFile, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { directoryBlobSchema, orgProfilePayloadSchema } from "../../packages/contracts/src/index";

const fixtureDir = new URL("./", import.meta.url);
const payloadDir = new URL("./payloads/", import.meta.url);
const outputPath = new URL("./fixtures.sql", import.meta.url);
const seriesOutputPath = new URL("./series.json", import.meta.url);
const snapshotId = "00000000-0000-4000-8000-000000000001";
const generatedAt = "2026-07-21T12:00:00Z";

type Payload = ReturnType<typeof orgProfilePayloadSchema.parse>;
type Directory = ReturnType<typeof directoryBlobSchema.parse>;

const historicalSeries: Record<string, { revenue: Array<number | null>; expenses: Array<number | null> }> = {
  "millbrook-community-rowing": { revenue: [520000, 560000, 590000, 615000, 640000], expenses: [500000, 525000, 545000, 570000, 590000] },
  "harborview-scholastic-oars": { revenue: [180000, null, 240000, 280000, 310000], expenses: [175000, null, 230000, 260000, 295000] },
  "pineglass-collegiate-club": { revenue: [330000, 365000, 395000, 425000, 455000], expenses: [320000, 350000, 380000, 405000, 430000] },
  "cobalt-reach-club": { revenue: [260000, 285000, 0, 315000, 340000], expenses: [248000, 270000, 0, 300000, 322000] }
};

function sqlText(value: string): string {
  return `'${value.replaceAll("'", "''")}'`;
}

function sqlJson(value: unknown): string {
  return `$fixture$${JSON.stringify(value)}$fixture$`;
}

function uuid(n: number): string {
  return `00000000-0000-4000-8000-${n.toString().padStart(12, "0")}`;
}

function expectedFyEnd(taxYear: number, fyeMonth: number): string {
  const year = fyeMonth <= 6 ? taxYear + 1 : taxYear;
  return `${year}-${fyeMonth.toString().padStart(2, "0")}-${fyeMonth === 2 ? "28" : [4, 6, 9, 11].includes(fyeMonth) ? "30" : "31"}`;
}

function periodLabel(taxYear: number, fyEnd: string): string {
  const month = Number(fyEnd.slice(5, 7));
  const fyYear = Number(fyEnd.slice(0, 4));
  const startMonth = month === 12 ? "Jan" : month === 6 ? "Jul" : month === 10 ? "Nov" : `month-${month}`;
  const startYear = month === 12 || month === 10 ? taxYear : taxYear;
  const endMonth = month === 12 ? "Dec" : month === 6 ? "Jun" : month === 10 ? "Oct" : `month-${month}`;
  return `FY${taxYear} (${startMonth} ${startYear}–${endMonth} ${fyYear})`;
}

function historicalRef(baseRef: any, value: number | null, taxYear: number, fyEnd: string, status: string, slug: string): any {
  const ref = structuredClone(baseRef);
  ref.value = value;
  ref.period = { tax_year: taxYear, fy_end: fyEnd, label: periodLabel(taxYear, fyEnd) };
  ref.source.filing_id = `${ref.source.filing_id.split("-")[0]}-fixture-${slug}-${taxYear}`;
  ref.source.source_path = value === null ? "coverage_missing" : ref.source.source_path;
  ref.source.raw_url = value === null ? null : ref.source.raw_url;
  ref.source.is_amended = status === "amended";
  ref.quality_state = value === null ? "unavailable" : "verified";
  return ref;
}

const payloadFiles = (await readdir(payloadDir)).filter((file) => file.endsWith(".json")).sort();
const payloads = (await Promise.all(payloadFiles.map(async (file) => {
  const raw = JSON.parse(await readFile(new URL(file, payloadDir), "utf8"));
  return orgProfilePayloadSchema.parse(raw);
}))).sort((a, b) => a.slug.localeCompare(b.slug));
const directory = directoryBlobSchema.parse(JSON.parse(await readFile(new URL("./directory.json", fixtureDir), "utf8"))) as Directory;
const payloadBySlug = new Map(payloads.map((payload) => [payload.slug, payload]));

if (directory.snapshot_id !== snapshotId) throw new Error("directory snapshot_id must match fixture snapshot");
if (directory.entries.length !== payloads.length) throw new Error("directory and payload counts differ");
for (const entry of directory.entries) {
  if (!payloadBySlug.has(entry.slug)) throw new Error(`directory slug has no payload: ${entry.slug}`);
}

const lines: string[] = [
  "-- Generated by bun db/fixtures/generate-sql.ts; do not edit by hand.",
  "BEGIN;",
  `INSERT INTO ops.publish_snapshot (id, ingest_run_id, status, manifest, created_at, activated_at) VALUES (${sqlText(snapshotId)}, NULL, 'active', ${sqlJson({ fixture: "phase1", payload_schema_version: 1, organization_count: payloads.length })}::jsonb, ${sqlText(generatedAt)}, ${sqlText(generatedAt)});`
];

for (const [index, payload] of payloads.entries()) {
  const header = payload.header;
  lines.push(`INSERT INTO core.organization (id, slug, display_name, legal_name, org_type, status, city, state, website, notes, created_at, updated_at) VALUES (${sqlText(payload.org_id)}, ${sqlText(payload.slug)}, ${sqlText(header.display_name)}, ${header.legal_name === null ? "NULL" : sqlText(header.legal_name)}, ${sqlText(header.org_type)}, 'included', ${header.city === null ? "NULL" : sqlText(header.city)}, ${header.state === null ? "NULL" : sqlText(header.state)}, ${header.website === null ? "NULL" : sqlText(header.website)}, ${sqlText(`Phase 1 fixture organization ${index + 1}`)}, ${sqlText(generatedAt)}, ${sqlText(generatedAt)});`);
}

const redstone = payloadBySlug.get("redstone-river-collective")!;
lines.push(`INSERT INTO core.organization_alias (id, organization_id, alias) VALUES (${sqlText(uuid(201))}, ${sqlText(redstone.org_id)}, ${sqlText("Redstone River Club")});`);
const juniper = payloadBySlug.get("juniper-creek-rowing")!;
const bayward = payloadBySlug.get("bayward-community-rowing")!;
lines.push(`INSERT INTO core.organization_relationship (id, from_organization_id, to_organization_id, relationship_type, notes) VALUES (${sqlText(uuid(202))}, ${sqlText(juniper.org_id)}, ${sqlText(bayward.org_id)}, 'boosters_for', ${sqlText("Fixture booster relationship")});`);

lines.push(`INSERT INTO read.published_snapshot (singleton, snapshot_id, created_at, updated_at) VALUES (true, ${sqlText(snapshotId)}, ${sqlText(generatedAt)}, ${sqlText(generatedAt)});`);

for (const entry of directory.entries) {
  const searchText = [entry.display_name, entry.slug, ...entry.aliases].join(" ");
  lines.push(`INSERT INTO read.org_directory (snapshot_id, organization_id, slug, display_name, coverage_state, aliases, search_text, fye_month, created_at) VALUES (${sqlText(snapshotId)}, ${sqlText(entry.org_id)}, ${sqlText(entry.slug)}, ${sqlText(entry.display_name)}, ${sqlText(entry.coverage_state)}, ${sqlJson(entry.aliases)}::jsonb, to_tsvector('simple', ${sqlText(searchText)}), ${entry.fye_month === null ? "NULL" : entry.fye_month}, ${sqlText(generatedAt)});`);
}

for (const payload of payloads) {
  lines.push(`INSERT INTO read.org_profile (snapshot_id, organization_id, payload, payload_schema_version, created_at) VALUES (${sqlText(snapshotId)}, ${sqlText(payload.org_id)}, ${sqlJson(payload)}::jsonb, ${payload.payload_schema_version}, ${sqlText(generatedAt)});`);
}

// The read.org_financial_series rows, also emitted as db/fixtures/series.json
// keyed by slug — the exact same tidy/long rows the SQL carries, with each
// row's source_ref, so the web tier can build AnnualSeries + a provenance map
// (keyed by series_key/tax_year) for chart-point SourceDrawers. Emitting it in
// lockstep here keeps the JSON and the SQL from ever drifting.
interface SeriesJsonRow {
  series_key: string;
  tax_year: number;
  fy_end: string;
  value: number | null;
  quality_state: string;
  is_amended: boolean;
  unit: string;
  source_ref: unknown;
}
const seriesJson: Record<string, SeriesJsonRow[]> = {};

let seriesId = 300;
for (const payload of payloads) {
  const rows: SeriesJsonRow[] = (seriesJson[payload.slug] = []);
  const directoryEntry = directory.entries.find((entry) => entry.slug === payload.slug)!;
  const financialFacts = payload.snapshot.filter((fact) => fact.ref.unit === "USD");
  const historical = historicalSeries[payload.slug];
  if (historical) {
    const revenueFact = payload.snapshot.find((fact) => fact.key === "total_revenue")!;
    const expenseFact = payload.snapshot.find((fact) => fact.key === "total_expenses")!;
    for (const [offset, taxYear] of [2020, 2021, 2022, 2023, 2024].entries()) {
      const coverage = payload.coverage.find((entry) => entry.tax_year === taxYear)!;
      for (const [seriesKey, fact, value] of [["total_revenue", revenueFact, historical.revenue[offset]], ["total_expenses", expenseFact, historical.expenses[offset]]] as const) {
        const fyEnd = coverage.fy_end ?? expectedFyEnd(taxYear, directoryEntry.fye_month!);
        const ref = historicalRef(fact.ref, value, taxYear, fyEnd, coverage.status, payload.slug);
        lines.push(`INSERT INTO read.org_financial_series (id, snapshot_id, organization_id, series_key, series_version, tax_year, fiscal_year_end, value, quality_state, is_amended, source_ref, created_at) VALUES (${sqlText(uuid(seriesId++))}, ${sqlText(snapshotId)}, ${sqlText(payload.org_id)}, ${sqlText(seriesKey)}, 1, ${taxYear}, ${sqlText(fyEnd)}, ${value === null ? "NULL" : value}, ${sqlText(ref.quality_state)}, ${ref.source.is_amended}, ${sqlJson(ref)}::jsonb, ${sqlText(generatedAt)});`);
        rows.push({ series_key: seriesKey, tax_year: taxYear, fy_end: fyEnd, value, quality_state: ref.quality_state, is_amended: ref.source.is_amended, unit: ref.unit, source_ref: ref });
      }
    }
  }
  for (const fact of financialFacts) {
    if (historical && (fact.key === "total_revenue" || fact.key === "total_expenses")) continue;
    const ref = fact.ref;
    lines.push(`INSERT INTO read.org_financial_series (id, snapshot_id, organization_id, series_key, series_version, tax_year, fiscal_year_end, value, quality_state, is_amended, source_ref, created_at) VALUES (${sqlText(uuid(seriesId++))}, ${sqlText(snapshotId)}, ${sqlText(payload.org_id)}, ${sqlText(fact.key)}, 1, ${ref.period.tax_year}, ${sqlText(ref.period.fy_end)}, ${ref.value === null ? "NULL" : ref.value}, ${sqlText(ref.quality_state)}, ${ref.source.is_amended}, ${sqlJson(ref)}::jsonb, ${sqlText(generatedAt)});`);
    rows.push({ series_key: fact.key, tax_year: ref.period.tax_year, fy_end: ref.period.fy_end, value: ref.value, quality_state: ref.quality_state, is_amended: ref.source.is_amended, unit: ref.unit, source_ref: ref });
  }
}

for (const payload of payloads) {
  for (const coverage of payload.coverage) {
    lines.push(`INSERT INTO read.org_filing_coverage (snapshot_id, organization_id, tax_year, status, created_at) VALUES (${sqlText(snapshotId)}, ${sqlText(payload.org_id)}, ${coverage.tax_year}, ${sqlText(coverage.status)}, ${sqlText(generatedAt)});`);
  }
}

for (const entry of directory.entries) {
  for (const cohortKey of entry.peer_cohorts) {
    lines.push(`INSERT INTO read.org_peer_cohort (snapshot_id, organization_id, cohort_key, reason_labels, created_at) VALUES (${sqlText(snapshotId)}, ${sqlText(entry.org_id)}, ${sqlText(cohortKey)}, ${sqlJson(["shared fixture peer cohort"])}::jsonb, ${sqlText(generatedAt)});`);
  }
}

for (const payload of payloads) {
  lines.push(`INSERT INTO read.org_slug_history (slug, snapshot_id, org_id, is_current, created_at) VALUES (${sqlText(payload.slug)}, ${sqlText(snapshotId)}, ${sqlText(payload.org_id)}, true, ${sqlText(generatedAt)});`);
}
lines.push(`INSERT INTO read.org_slug_history (slug, snapshot_id, org_id, is_current, created_at) VALUES (${sqlText("redstone-river-club-301s")}, ${sqlText(snapshotId)}, ${sqlText(redstone.org_id)}, false, ${sqlText(generatedAt)});`);
lines.push("COMMIT;", "");

await writeFile(outputPath, lines.join("\n"));
await writeFile(seriesOutputPath, `${JSON.stringify(seriesJson, null, 2)}\n`);
console.log(`Wrote ${outputPath.pathname} (${payloads.length} payloads, ${seriesId - 300} financial rows).`);
console.log(`Wrote ${seriesOutputPath.pathname} (${Object.keys(seriesJson).length} orgs).`);
